<?php 
$articulos = array( 0 => array ('Codigo' => '#1234',
                                'Imagen' => 'reloj',
                                'Texto'=> 'Led Adjustable Sports Bracelet Watch',
                                'StockActual' => 30,
                                'StockMinimo' => 20,
                                'Precio'=> 6.99),
                    1 => array ('Codigo' =>'#2345',
                             'Imagen' => 'auriculares1',
                              'Texto'=> 'Wireless in-ear headphones Black',
                                'StockActual' => 40,
                                'StockMinimo' => 20,
                                'Precio'=> 59.99),
                  2 => array ('Codigo' => '#3456',
                                'Imagen' => 'auriculares2',
                                'Texto'=> '	White wireless headset',
                               'StockActual' => 20,
                               'StockMinimo' => 25,
                                'Precio'=>  47.99),
                   3 => array ('Codigo' => '#4567',
                               'Imagen' => 'soporte',
                               'Texto'=> 'Extendable Support Cell Phone for Notebook',
                               'StockActual' => 80,
                            'StockMinimo' => 40,
                            'Precio'=> 11.99),
                    4 => array ('Codigo' => '#5678',
                               'Imagen' => 'funda',
                               'Texto'=> '	Sports Case For iPhone Armband',
                                'StockActual' => 100,
                               'StockMinimo' => 50,
                               'Precio'=>  47.99)
                               
 );
?>